---
- name: RAINLOOP WEBMAIL SETUP
  hosts: localhost
  connection: local
  roles:
#    - setup-local-registry
#    - setup-rainloop

- name: Configure the Podman container
  hosts: rainloop
  connection: podman
  roles:
    - build-rainloop
