---
- hosts: localhost
  connection: local
  roles:
    - setup-local-registry
    - setup-rainloop

- hosts: rainloop
  connection: podman
  roles:
    - build-rainloop

- hosts: localhost
  name: commit image 
  connection: local
  tasks:
    - command: podman commit rainloop rainloop-image

