---

- name: Add Docker's GPG key
  rpm_key:
    url: "http://download.docker.com/linux/centos/gpg"
    state: present
    validate_certs: no
 
- name: Add Docker repo
  yum_repository:
    name: docker
    repo: https://download.docker.com/linux/centos/docker-ce.repo
    state: present

- name: Install Docker-ce package
  yum:
    name: docker-ce
 
- name: Create private registry dir
  file:
    path: ~/docker/registry
    state: directory

- name: Start the private registry
  command: "docker run -d -p 5000:5000 --name private-registry --restart=always -v ~/docker/registry:/var/lib/registry registry:2"
  register: start_reg
