---

- name: Add Docker's GPG key
  rpm_key:
    key: "http://download.docker.com/linux/centos/gpg"
    state: present
 
- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: Install Docker and docker-distribution packages
  yum:
    name: [ 'docker', 'docker-distribution' ]

- name: Copy the daemon.json to allow insecure registry
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: start and enable docker
  service:
    name: docker
    state: started
    enabled: yes

- name: start and enable docker-distribution
  service:
    name: docker-distribution
    state: started
    enabled: yes

 
